# Generated by Django 3.1 on 2020-09-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='available',
        ),
    ]
