# Generated by Django 3.1 on 2020-09-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200921_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='digital',
        ),
    ]
