# Generated by Django 3.1 on 2020-09-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200921_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='digital',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
    ]
