# Generated by Django 3.1 on 2020-09-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_deliver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='available',
        ),
    ]
