# Generated by Django 3.1 on 2020-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200925_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prepare',
            field=models.BooleanField(default=False),
        ),
    ]
